# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App_Instagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App_Instagram
	pod 'FirebaseCore'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'ActiveLabel'
	pod 'PromiseKit'
	pod 'CodableFirebase'
	pod 'Firebase/DynamicLinks'
  pod 'FirebaseFirestore'
end
